#!/usr/bin/env sh

: ${AUTOCOMPLETE}
: ${CATEGORIES_AS_TABS}
: ${DEBUG}
: ${DEFAULT_LANGUAGE}
: ${DEFAULT_LOCALE}
: ${DEFAULT_THEME}
: ${ENABLE_METRICS}
: ${ENGINES}
: ${FORMATS}
: ${IMAGE_PROXY}
: ${PLUGINS}
: ${PREFERENCES_LOCK}
: ${PUBLIC_INSTANCE}
: ${QUERY_IN_TITLE}
: ${SAFE_SEARCH}
: ${SEARCH_ON_CATEGORY_SELECT}
: ${SECRET_KEY}
: ${URL_FORMATTING}

{
    yq -i ".server.secret_key = env(SECRET_KEY)" /etc/searxng/settings.yml

    unset SECRET_KEY

    rm /run/searxng-configure/environment/SECRET_KEY
}

{
    yq -i ".general.debug = env(DEBUG)"                                    /etc/searxng/settings.yml
    yq -i ".general.enable_metrics = env(ENABLE_METRICS)"                  /etc/searxng/settings.yml
    yq -i ".plugins[].active = false"                                      /usr/local/searxng/searx/settings.yml
    yq -i ".search.autocomplete = env(AUTOCOMPLETE)"                       /etc/searxng/settings.yml
    yq -i ".search.default_lang = env(DEFAULT_LANGUAGE)"                   /etc/searxng/settings.yml
    yq -i ".search.safe_search = env(SAFE_SEARCH)"                         /etc/searxng/settings.yml
    yq -i ".server.image_proxy = env(IMAGE_PROXY)"                         /etc/searxng/settings.yml
    yq -i ".server.public_instance = env(PUBLIC_INSTANCE)"                 /etc/searxng/settings.yml
    yq -i ".ui.default_locale = env(DEFAULT_LOCALE)"                       /etc/searxng/settings.yml
    yq -i ".ui.default_theme = env(DEFAULT_THEME)"                         /etc/searxng/settings.yml
    yq -i ".ui.query_in_title = env(QUERY_IN_TITLE)"                       /etc/searxng/settings.yml
    yq -i ".ui.search_on_category_select = env(SEARCH_ON_CATEGORY_SELECT)" /etc/searxng/settings.yml
    yq -i ".ui.url_formatting = env(URL_FORMATTING)"                       /etc/searxng/settings.yml
}

if [ -f /usr/local/searxng/searx/infopage/en/donate.md ]; then
    yq -i ".general.donation_url = true"  /etc/searxng/settings.yml
fi

if [ -n "$CATEGORIES_AS_TABS" ]; then
    yq -i '.categories_as_tabs = {}
        | (
            strenv(CATEGORIES_AS_TABS)
            | split(",")
            | map(trim)
        ) as $category
        | .categories_as_tabs[$category[]] = ~
    ' /etc/searxng/settings.yml
fi

if [ -n "$ENGINES" ]; then
    yq -i ".engines[].disabled = true" /usr/local/searxng/searx/settings.yml

    yq -i '.engines += (
        strenv(ENGINES)
        | split(",")
        | map(trim)
        | map({
            "name": .,
            "disabled": false
        })
    )' /etc/searxng/settings.yml
fi

if [ -n "$FORMATS" ]; then
    yq -i '.search.formats = (
        strenv(FORMATS)
        | split(",")
        | map(trim)
    ) ' /etc/searxng/settings.yml
fi

if [ -n "$PLUGINS" ]; then
    yq -i '.plugins = {}
        | (
            strenv(PLUGINS)
            | split(",")
            | map(trim)
            | .[]
        ) as $plugin
        | .plugins["searx.plugins." + $plugin + ".SXNGPlugin"].active = true
    ' /etc/searxng/settings.yml
fi

if [ -n "$PREFERENCES_LOCK" ]; then
    yq -i '.preferences.lock = (
        strenv(PREFERENCES_LOCK)
        | split(",")
        | map(trim)
    ) ' /etc/searxng/settings.yml
fi

sed -E "s|: ~$|:|" -i /etc/searxng/settings.yml

ln -fs /usr/local/searxng/searx/limiter.toml /etc/searxng/limiter.toml
