name: Cypress e2e testing

on:
  workflow_call:

jobs:
  cypress:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build app image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: app
          tags: |
            localhost:5000/app

      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: cypress
          tags: |
            localhost:5000/cypress

      - name: Run tests
        run: |
          docker network create test-network
          docker run --rm --net test-network --name searx -d localhost:5000/app
          docker run --rm --net test-network --name searx-test -v ${PWD}/tests/e2e/artifacts/:/tests/e2e/artifacts/ localhost:5000/cypress run --reporter junit --reporter-options "mochaFile=artifacts/reports/junit-[hash].xml"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            tests/e2e/artifacts
        if: failure()

      - name: Report test results
        uses: dorny/test-reporter@v1
        with:
          name: Cypress test report
          path: tests/e2e/artifacts/reports/junit-*.xml
          reporter: jest-junit
        if: success() || failure()
