name: Renovate dependencies

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      RENOVATE_BRANCH_NAME:
        description: "Branch name passed to Renovate"
        type: string
        required: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Renovate app token
        id: renovate-app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}
          repositories: ${{ toJSON(github.repository) }}

      - if: inputs.RENOVATE_BRANCH_NAME
        run: echo "RENOVATE_BRANCH_NAME=${{ inputs.RENOVATE_BRANCH_NAME }}" >> $GITHUB_ENV

      - name: Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          token: ${{ steps.renovate-app-token.outputs.token }}
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTOMERGE: true
          RENOVATE_AUTOMERGE_STRATEGY: merge-commit
          RENOVATE_USE_BASE_BRANCH_CONFIG: merge
