name: Testing

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}

      - name: Build images and run tests
        shell: bash
        run: |
          set -e
          docker build . -t searx --progress plain --target app
          docker build . -t searx-test --progress plain --target cypress
          docker network create test-network
          docker run --rm --net test-network --name searx -d searx
          docker run --rm --net test-network --name searx-test -v ${PWD}/tests/e2e/artifacts/:/tests/e2e/artifacts/ searx-test run --browser firefox --reporter junit --reporter-options "mochaFile=artifacts/reports/junit-[hash].xml"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            tests/e2e/artifacts
        if: failure()

      - name: Report test results
        uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: tests/e2e/artifacts/reports/junit-*.xml
          reporter: java-junit
        if: success() || failure()
