name: Pull requests

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:

jobs:
  cypress:
    uses: ./.github/workflows/_cypress.yaml

  auto-merge:
    runs-on: ubuntu-latest
    needs:
      - cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Renovate app token
        id: renovate-app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}
          repositories: ${{ toJSON(github.repository) }}

      - name: Dispatch Renovate workflow
        run: gh workflow run _renovate.yaml -f RENOVATE_BRANCH_NAME=${GITHUB_HEAD_REF}
        env:
          GITHUB_TOKEN: ${{ steps.renovate-app-token.outputs.token }}
